version: '3.8'

# https://docs.docker.com/network/drivers/: bridge mode by default
networks:
    operations-net:
    services-net:

volumes:
  # Metrics storage
    prometheus-data:
        driver: local
  # Config files and dashboards configurations
    grafana-data:
        driver: local

services:
    # This service scrapes metrics over http on other services and systems
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        expose:
            - 9090
        ports:
            - 9090:9090
        networks:
            - operations-net
            - services-net

    grafana:
        image: grafana/grafana-oss:latest
        container_name: grafana
        restart: unless-stopped
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=${GR_SMTP_HOST}
            - GF_SMTP_USER=${GF_SMTP_FROM_ADDRESS}
            - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
            - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
            - GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME}
            - GF_SMTP_SKIP_VERIFY=true
        expose:
            - 3000
        ports:
            - 3000:3000
        depends_on:
            - rest-api
            - apache
        networks:
            - operations-net

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        restart: unless-stopped
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        expose:
            - 9100
        networks:
            - services-net

    rest-api:
        image: python:3.10
        container_name: rest-api
        restart: unless-stopped
        command: /bin/sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 5001"
        volumes:
            - ./api:/app
        working_dir: /app
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - "5001:5001"
        depends_on:
            - postgres
        networks:
            - services-net

    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_MAX_CONNECTIONS: 1000
        ports:
            - 5432:5432
        networks:
            - services-net
        restart: unless-stopped

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        container_name: postgres-exporter
        restart: unless-stopped
        environment:
            - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
        expose:
            - 9187
        ports:
            - 9187:9187
        networks:
            - services-net

    apache:
        build: ./apache
        container_name: apache
        ports:
            - "8080:80"
        networks:
            - services-net
        restart: unless-stopped

    apache-exporter:
        image: lusotycoon/apache-exporter:latest
        container_name: apache-exporter
        restart: unless-stopped
        expose:
            - 9117
        ports:
            - 9117:9117
        networks:
            - services-net
        command:
            - '--scrape_uri=http://apache:80/server-status?auto'
            
    blackbox-exporter:
        image: prom/blackbox-exporter:latest
        container_name: blackbox-exporter
        restart: unless-stopped
        volumes:
            - ./blackbox/blackbox.yml:/config/blackbox.yml
        command:
            - '--config.file=/config/blackbox.yml'
        expose:
            - 9115
        ports:
            - 9115:9115
        networks:
            - services-net

    pushgateway:
        # https://github.com/prometheus/pushgateway
        image: prom/pushgateway:latest
        container_name: pushgateway
        restart: unless-stopped
        ports:
            - 9091:9091
        networks:
            - services-net

    k6:
        build: ./k6-cron
        container_name: k6
        restart: unless-stopped
        environment:
            - PROMETHEUS_PUSHGATEWAY_URL=http://pushgateway:9091
        depends_on:
            - apache
        networks:
            - services-net
