global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Static configuration list of targets for metrics polling.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
        - targets: ['node-exporter:9100']
