apiVersion: 1

contactPoints:
    - orgId: 1
      name: interpol-contacts
      receivers:
        - uid: admbxbfvjr7y8e
          type: email
          settings:
            addresses: <learodriguez@itba.edu.ar>;<robrodriguez@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false
    - orgId: 1
      name: monitor-net-contacts
      receivers:
        - uid: fdmbx94g4ucqoc
          type: email
          settings:
            addresses: <ldagostino@itba.edu.ar>;<fcupito@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false

policies:
    - orgId: 1
      receiver: monitor-net-contacts
      routes:
        - receiver: interpol-contacts
          object_matchers:
            - - security
              - =
              - "1"
        - receiver: monitor-net-contacts
          object_matchers:
            - - security
              - =
              - "2"
