apiVersion: 1

contactPoints:
    - orgId: 1
      name: interpol-contacts
      receivers:
        - uid: admbxbfvjr7y8e
          type: email
          settings:
            addresses: <learodriguez@itba.edu.ar>;<robrodriguez@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false
    - orgId: 1
      name: monitor-net-contacts
      receivers:
        - uid: fdmbx94g4ucqoc
          type: email
          settings:
            addresses: <ldagostino@itba.edu.ar>;<fcupito@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false

policies:
    - orgId: 1
      receiver: monitor-net-contacts
      routes:
        - receiver: interpol-contacts
          object_matchers:
            - - security
              - =
              - "1"
        - receiver: monitor-net-contacts
          object_matchers:
            - - security
              - =
              - "2"

groups:
    - orgId: 1
      name: InterpolEvGroup
      folder: Interpol
      interval: 10s
      rules:
        - uid: cdmbnu0lwvrb4d
          title: Wanted Criminals Found
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                datasource:
                    type: prometheus
                    uid: PC68CF569CB931581
                disableTextWrap: false
                editorMode: builder
                exemplar: false
                expr: sum_over_time(dni_found_total[$__interval])
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: D
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                datasource:
                    type: prometheus
                    uid: PC68CF569CB931581
                disableTextWrap: false
                editorMode: builder
                expr: changes(dni_found_total[10s])
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: D
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: D
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: edmbk6u8pzrpcd
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            __dashboardUid__: edmbk6u8pzrpcd
            __panelId__: "1"
            description: There is a wanted criminal trying to pass through the migration post in the airport.
            summary: Wanted criminal detected
          labels:
            security: "1"
          isPaused: false
