apiVersion: 1

contactPoints:
    - orgId: 1
      name: interpol-contacts
      receivers:
        - uid: admbxbfvjr7y8e
          type: email
          settings:
            addresses: <learodriguez@itba.edu.ar>;<robrodriguez@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false
    - orgId: 1
      name: monitor-net-contacts
      receivers:
        - uid: fdmbx94g4ucqoc
          type: email
          settings:
            addresses: <ldagostino@itba.edu.ar>;<fcupito@itba.edu.ar>
            singleEmail: true
          disableResolveMessage: false

policies:
    - orgId: 1
      receiver: monitor-net-contacts
      routes:
        - receiver: interpol-contacts
          object_matchers:
            - - security
              - =
              - "1"
        - receiver: monitor-net-contacts
          object_matchers:
            - - security
              - =
              - "2"

groups:
    - orgId: 1
      name: Ops. Latency Ev. Group
      folder: Operations Latency Alarms
      interval: 1m
      rules:
        - uid: admxg9ri3ftvkc
          title: DNI Latency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                editorMode: code
                expr: rest_api_request_latency_bucket{le="+Inf", endpoint="check_dni"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                datasource:
                    type: prometheus
                    uid: PC68CF569CB931581
                editorMode: code
                expr: rest_api_request_latency_bucket{le="0.2", endpoint="check_dni"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: D
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $A - $D > $D
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: math
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: Endpoint /dni is overloaded with requests. You might want to check it out.
            summary: 'Overloaded endpoint: /dni'
          labels:
            security: "2"
          isPaused: false
        - uid: bdmxgd960jmdcc
          title: Flight Latency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                editorMode: code
                expr: rest_api_request_latency_bucket{le="+Inf", endpoint="check_flight"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                datasource:
                    type: prometheus
                    uid: PC68CF569CB931581
                editorMode: code
                expr: rest_api_request_latency_bucket{le="0.2", endpoint="check_flight"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: D
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $A - $D > $D
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: math
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: Endpoint /flights is overloaded with requests. You might want to check it out.
            summary: 'Overloaded endpoint: /flights'
          labels:
            security: "2"
          isPaused: false
        - uid: admxgetve2bcwb
          title: Immigration Latency
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                editorMode: code
                expr: rest_api_request_latency_bucket{le="+Inf", endpoint="create_immigration_entry"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                datasource:
                    type: prometheus
                    uid: PC68CF569CB931581
                editorMode: code
                expr: rest_api_request_latency_bucket{le="0.2", endpoint="create_immigration_entry"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: D
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $A - $D > $D
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: math
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            description: Endpoint /immigration is overloaded with requests. You might want to check it out.
            summary: 'Overloaded endpoint: /immigration'
          labels:
            security: "2"
          isPaused: false
    - orgId: 1
      name: Ops Ev. Group
      folder: Operations Alarms
      interval: 10s
      rules:
        - uid: edmpg807n9gqoa
          title: Apache Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                disableTextWrap: false
                editorMode: builder
                expr: probe_success{instance=~"http://apache:80"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            summary: Apache Down
          labels:
            security: "2"
          isPaused: false
        - uid: cdmphkhat1dkwe
          title: Rest API Down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                editorMode: code
                expr: probe_success{instance="http://rest-api:5001"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            summary: Rest API down
          labels:
            security: "2"
          isPaused: false
    - orgId: 1
      name: Devs Ev. Group
      folder: Developers Alarms
      interval: 10s
      rules:
        - uid: fdmpit8lo3cw0d
          title: Emergency Apache Down
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                disableTextWrap: false
                editorMode: builder
                expr: probe_success{instance=~"http://apache:80"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Emergency! Apache has been down for 1m!
          labels:
            security: "1"
          isPaused: false
        - uid: edmpiz3qj4f0gf
          title: Emergency Rest API Down
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PC68CF569CB931581
              model:
                editorMode: code
                expr: probe_success{instance="http://rest-api:5001"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                            - 0
                        type: lt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          dashboardUid: ""
          panelId: 0
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: Emergency! Rest API has been down for 1m!
          labels:
            security: "1"
          isPaused: false
