global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Static configuration list of targets for metrics polling.
scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
        - targets: ['node-exporter:9100']

  - job_name: 'rest-api'
    static_configs:
      - targets: ['rest-api:5001']

  - job_name: 'apache-exporter'
    static_configs:
        - targets: ['apache-exporter:9117']
  
  - job_name: 'postgres-exporter'
    static_configs:
        - targets: ['postgres-exporter:9187']
 
  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://apache:80
        - http://rest-api:5001
        - http://apache:80/delay
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
  
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']