global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Static configuration list of targets for metrics polling.
scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
        - targets: ['node-exporter:9100']

  - job_name: 'rest-api'
    static_configs:
      - targets: ['rest-api:5001']