{
 "title": "Rest-api",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(rest_api_requests_total[$__rate_interval])",
     "legendFormat": "Request Total"
    },
    {
     "expr": "increase(rest_api_requests_dni_total[$__rate_interval])",
     "legendFormat": "Requests to /dni"
    },
    {
     "expr": "increase(rest_api_requests_flight_total[$__rate_interval])",
     "legendFormat": "Requests to /flights"
    },
    {
     "expr": "increase(rest_api_requests_immigration_total[$__rate_interval])",
     "legendFormat": "Requests to /immigration"
    }
   ]
  },
  {
   "title": "Server Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rest_api_server_error_count_total{endpoint=~\"check_dni|check_flight|create_immigration_entry\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_flight|check_dni|create_immigration_entry\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /flights Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_flight\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /dni Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_dni\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /immigration Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"create_immigration_entry\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Wanted Criminals Found",
   "type": "timeseries",
   "description": "The amount of criminals from Interpol database found up to now.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum_over_time(rest_api_dni_found_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}