{
 "title": "Rest-api",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rest_api_requests_total - (rest_api_requests_total offset $__rate_interval)",
     "legendFormat": "Request Total"
    },
    {
     "expr": "rest_api_requests_dni_total - (rest_api_requests_dni_total offset $__rate_interval)",
     "legendFormat": "Requests to /dni"
    },
    {
     "expr": "rest_api_requests_flight_total - (rest_api_requests_flight_total offset $__rate_interval)",
     "legendFormat": "Requests to /flights"
    },
    {
     "expr": "rest_api_requests_immigration_total - (rest_api_requests_immigration_total offset $__rate_interval)",
     "legendFormat": "Requests to /immigration"
    }
   ]
  },
  {
   "title": "Server Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rest_api_server_error_count_total{endpoint=~\"check_dni|check_flight|create_immigration_entry\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Interpol Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wanted Criminals Found",
     "type": "timeseries",
     "description": "The amount of criminals from Interpol database found up to now.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum_over_time(rest_api_dni_found_total[$__interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Latency Across Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_flight|check_dni|create_immigration_entry\"} - (rest_api_request_latency_bucket{endpoint=~\"check_flight|check_dni|create_immigration_entry\"} offset $__rate_interval)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /flights Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_flight\"} - (rest_api_request_latency_bucket{endpoint=~\"check_flight\"} offset $__rate_interval)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /immigration Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"create_immigration_entry\"} - (rest_api_request_latency_bucket{endpoint=~\"create_immigration_entry\"} offset $__rate_interval)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution - /dni Endpoint",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "rest_api_request_latency_bucket{endpoint=~\"check_dni\"} - (rest_api_request_latency_bucket{endpoint=~\"check_dni\"} offset $__rate_interval)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}